// <auto-generated />
using System;
using HamsterWars_DatabaseSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HamsterWarsDatabaseSQL.Migrations
{
    [DbContext(typeof(HamsterContext))]
    [Migration("20221207134018_UpdatedMatchResult")]
    partial class UpdatedMatchResult
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HamsterWars_DatabaseSQL.Models.Hamster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FavFood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Games")
                        .HasColumnType("int");

                    b.Property<string>("ImgName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Loves")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hamsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 2,
                            FavFood = "Carrot",
                            Games = 0,
                            ImgName = "hamster-1.jpg",
                            Losses = 0,
                            Loves = "Killing babies",
                            Name = "Destroyer of Worlds",
                            Wins = 0
                        },
                        new
                        {
                            Id = 2,
                            Age = 1,
                            FavFood = "Cucumber",
                            Games = 0,
                            ImgName = "hamster-2.jpg",
                            Losses = 0,
                            Loves = "Helping elderly",
                            Name = "Savior of Worlds",
                            Wins = 0
                        },
                        new
                        {
                            Id = 3,
                            Age = 0,
                            FavFood = "Apple",
                            Games = 0,
                            ImgName = "hamster-3.jpg",
                            Losses = 0,
                            Loves = "Confronting Evil",
                            Name = "Protector of the Wastelands",
                            Wins = 0
                        },
                        new
                        {
                            Id = 4,
                            Age = 4,
                            FavFood = "Pepper",
                            Games = 0,
                            ImgName = "hamster-4.jpg",
                            Losses = 0,
                            Loves = "Sleeping",
                            Name = "Grand Hamster",
                            Wins = 0
                        },
                        new
                        {
                            Id = 5,
                            Age = 2,
                            FavFood = "Banana",
                            Games = 0,
                            ImgName = "hamster-5.jpg",
                            Losses = 0,
                            Loves = "Yellow things",
                            Name = "Yellow Devil",
                            Wins = 0
                        },
                        new
                        {
                            Id = 6,
                            Age = 1,
                            FavFood = "Snickers",
                            Games = 0,
                            ImgName = "hamster-6.jpg",
                            Losses = 0,
                            Loves = "Helping others",
                            Name = "Wingman",
                            Wins = 0
                        },
                        new
                        {
                            Id = 7,
                            Age = 1,
                            FavFood = "Sugar",
                            Games = 0,
                            ImgName = "hamster-7.jpg",
                            Losses = 0,
                            Loves = "Reading books",
                            Name = "Rincewind",
                            Wins = 0
                        },
                        new
                        {
                            Id = 8,
                            Age = 7,
                            FavFood = "Candy",
                            Games = 0,
                            ImgName = "hamster-8.jpg",
                            Losses = 0,
                            Loves = "Small things",
                            Name = "Red dwarf",
                            Wins = 0
                        },
                        new
                        {
                            Id = 9,
                            Age = 4,
                            FavFood = "Ice cream",
                            Games = 0,
                            ImgName = "hamster-9.jpg",
                            Losses = 0,
                            Loves = "IoT",
                            Name = "Snowden",
                            Wins = 0
                        },
                        new
                        {
                            Id = 10,
                            Age = 3,
                            FavFood = "Ice cream",
                            Games = 0,
                            ImgName = "hamster-10.jpg",
                            Losses = 0,
                            Loves = "Snowmen",
                            Name = "Ice Queen",
                            Wins = 0
                        });
                });

            modelBuilder.Entity("HamsterWars_DatabaseSQL.Models.HamsterMatches", b =>
                {
                    b.Property<int>("HamsterId")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.HasKey("HamsterId", "MatchId");

                    b.HasIndex("MatchId");

                    b.ToTable("HamsterMatches");

                    b.HasData(
                        new
                        {
                            HamsterId = 1,
                            MatchId = 1
                        },
                        new
                        {
                            HamsterId = 2,
                            MatchId = 1
                        },
                        new
                        {
                            HamsterId = 4,
                            MatchId = 2
                        },
                        new
                        {
                            HamsterId = 7,
                            MatchId = 2
                        },
                        new
                        {
                            HamsterId = 3,
                            MatchId = 3
                        },
                        new
                        {
                            HamsterId = 1,
                            MatchId = 3
                        },
                        new
                        {
                            HamsterId = 5,
                            MatchId = 4
                        },
                        new
                        {
                            HamsterId = 8,
                            MatchId = 4
                        },
                        new
                        {
                            HamsterId = 4,
                            MatchId = 5
                        },
                        new
                        {
                            HamsterId = 9,
                            MatchId = 5
                        },
                        new
                        {
                            HamsterId = 10,
                            MatchId = 6
                        },
                        new
                        {
                            HamsterId = 2,
                            MatchId = 6
                        },
                        new
                        {
                            HamsterId = 8,
                            MatchId = 7
                        },
                        new
                        {
                            HamsterId = 3,
                            MatchId = 7
                        });
                });

            modelBuilder.Entity("HamsterWars_DatabaseSQL.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCompleted = false,
                            StartDate = new DateTime(2022, 12, 7, 14, 40, 18, 119, DateTimeKind.Local).AddTicks(3159)
                        },
                        new
                        {
                            Id = 2,
                            IsCompleted = true,
                            StartDate = new DateTime(2022, 12, 7, 14, 40, 18, 119, DateTimeKind.Local).AddTicks(3189)
                        },
                        new
                        {
                            Id = 3,
                            IsCompleted = false,
                            StartDate = new DateTime(2022, 12, 7, 14, 40, 18, 119, DateTimeKind.Local).AddTicks(3191)
                        },
                        new
                        {
                            Id = 4,
                            IsCompleted = false,
                            StartDate = new DateTime(2022, 12, 7, 14, 40, 18, 119, DateTimeKind.Local).AddTicks(3193)
                        },
                        new
                        {
                            Id = 5,
                            IsCompleted = true,
                            StartDate = new DateTime(2022, 12, 7, 14, 40, 18, 119, DateTimeKind.Local).AddTicks(3194)
                        },
                        new
                        {
                            Id = 6,
                            IsCompleted = true,
                            StartDate = new DateTime(2022, 12, 7, 14, 40, 18, 119, DateTimeKind.Local).AddTicks(3196)
                        },
                        new
                        {
                            Id = 7,
                            IsCompleted = true,
                            StartDate = new DateTime(2022, 12, 7, 14, 40, 18, 119, DateTimeKind.Local).AddTicks(3198)
                        });
                });

            modelBuilder.Entity("HamsterWars_DatabaseSQL.Models.MatchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LooserId")
                        .HasColumnType("int");

                    b.Property<int>("LooserScore")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("WinnerId")
                        .HasColumnType("int");

                    b.Property<int>("WinnerScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LooserId");

                    b.HasIndex("WinnerId");

                    b.ToTable("MatchResults");
                });

            modelBuilder.Entity("HamsterWars_DatabaseSQL.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HamsterId")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Votes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HamsterId = 4,
                            MatchId = 1
                        },
                        new
                        {
                            Id = 2,
                            HamsterId = 4,
                            MatchId = 2
                        },
                        new
                        {
                            Id = 3,
                            HamsterId = 7,
                            MatchId = 2
                        },
                        new
                        {
                            Id = 4,
                            HamsterId = 7,
                            MatchId = 2
                        },
                        new
                        {
                            Id = 5,
                            HamsterId = 7,
                            MatchId = 2
                        },
                        new
                        {
                            Id = 6,
                            HamsterId = 7,
                            MatchId = 2
                        },
                        new
                        {
                            Id = 7,
                            HamsterId = 4,
                            MatchId = 2
                        },
                        new
                        {
                            Id = 8,
                            HamsterId = 4,
                            MatchId = 2
                        },
                        new
                        {
                            Id = 9,
                            HamsterId = 7,
                            MatchId = 2
                        },
                        new
                        {
                            Id = 10,
                            HamsterId = 4,
                            MatchId = 5
                        },
                        new
                        {
                            Id = 11,
                            HamsterId = 10,
                            MatchId = 6
                        },
                        new
                        {
                            Id = 12,
                            HamsterId = 8,
                            MatchId = 7
                        });
                });

            modelBuilder.Entity("HamsterWars_DatabaseSQL.Models.HamsterMatches", b =>
                {
                    b.HasOne("HamsterWars_DatabaseSQL.Models.Hamster", null)
                        .WithMany()
                        .HasForeignKey("HamsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamsterWars_DatabaseSQL.Models.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HamsterWars_DatabaseSQL.Models.MatchResult", b =>
                {
                    b.HasOne("HamsterWars_DatabaseSQL.Models.Hamster", "Looser")
                        .WithMany()
                        .HasForeignKey("LooserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamsterWars_DatabaseSQL.Models.Hamster", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Looser");

                    b.Navigation("Winner");
                });
#pragma warning restore 612, 618
        }
    }
}
